version: 2.0
jobs:
  build_gcc_6:
    docker:
      - image: kitware/cmake:build-linux-x86_64-base-2019-08-09
    steps:
      - checkout
      - run: mkdir -p build && cd build
      - run: cmake .. && make
      - run: ./test/ExampleTests
  build_gcc_latest:
    docker:
      - image: kitware/cmake:latest
    steps:
      - checkout
      - run: mkdir -p build && cd build
      - run: cmake .. && make
      - run: ./test/ExampleTests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
      - build_gcc_latest
