version: 2.0
jobs:
  build_gcc_6:
    docker:
      - image: gcc:6
    steps:
      - checkout
      - run: apt-get update -y &&   apt-get install cmake -y
      - run: mkdir -p build && cd build
      - run: cmake .. && make
      - run: ./test/ExampleTests
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: apt-get update -y &&   apt-get install cmake -y
      - run: mkdir -p build && cd build
      - run: cmake .. && make
      - run: ./test/ExampleTests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_6
      - build_gcc_latest
